import { Player, Manager, Team, CommunityPost, PlayerStats } from '../types';

export const SKILLS_LIST = [
  'Double Touch',
  'Marseille Turn',
  'Flip Flap',
  'Sole Control',
  'Heading',
  'Long Range Drive',
  'Chip Shot Control',
  'Long Range Shooting',
  'Knuckle Shot',
  'Dipping Shot',
  'Rising Shot',
  'Acrobatic Finishing',
  'Heel Trick',
  'One-touch Pass',
  'Through Passing',
  'Weighted Pass',
  'Pinpoint Crossing',
  'Outside Curler',
  'Rabona',
  'No-look Pass',
  'Low Lofted Pass',
  'Interception',
  'Sliding Tackle',
  'Clearing',
  'Man Marking',
  'Captaincy',
  'Super-sub',
  'Fighting Spirit',
  'Aerial Superiority',
  'Track Back',
  'Blocker',
  'GK Penalty Saver',
  'GK High Point Catch',
  'GK Low Reach'
];

export const PLAYSTYL_LIST = [
  'Offensive Wingback',
  'Goal Poacher',
  'Creative Playmaker',
  'Roaming Flank',
  'Anchor Man',
  'Defensive Goalkeeper',
  'Target Man',
  'Box-to-Box',
  'Build Up',
  'Destroyer',
  'Classic No. 10',
  'Hole Player'
];

export const TEAMS_DB: Team[] = [
  { id: 't1', name: 'Marlboro FC', logo: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=100&auto=format&fit=crop&q=60', league: 'English League' },
  { id: 't2', name: 'Lombardia NA', logo: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?w=100&auto=format&fit=crop&q=60', league: 'Italian League' },
  { id: 't3', name: 'Madrid Chamartin B', logo: 'https://images.unsplash.com/photo-1518063319789-7217e6706b04?w=100&auto=format&fit=crop&q=60', league: 'Spanish League' },
  { id: 't4', name: 'Passion Golden Wind', logo: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=100&auto=format&fit=crop&q=60', league: 'Anime League' },
  { id: 't5', name: 'Underground Skeletons', logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=60', league: 'Cosmic League' }
];

export const MANAGERS_DB: Manager[] = [
  {
    id: 'm1',
    name: 'L. Roman (P. Guardiola)',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    possession: 88,
    quickCounter: 76,
    longBallCounter: 60,
    outWide: 70,
    longBall: 40,
    bonusType: 'passing',
    bonusValue: 2
  },
  {
    id: 'm2',
    name: 'G. Zeitzler (J. Klopp)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    possession: 65,
    quickCounter: 87,
    longBallCounter: 70,
    outWide: 68,
    longBall: 45,
    bonusType: 'speed',
    bonusValue: 2
  },
  {
    id: 'm3',
    name: 'C. Valbuena (Simeone)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    possession: 50,
    quickCounter: 72,
    longBallCounter: 85,
    outWide: 60,
    longBall: 50,
    bonusType: 'defending',
    bonusValue: 2
  },
  {
    id: 'm4',
    name: 'Spider-Sponsor (Tony Stark)',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    possession: 85,
    quickCounter: 85,
    longBallCounter: 85,
    outWide: 85,
    longBall: 85,
    bonusType: 'all',
    bonusValue: 3
  }
];

export const PLAYERS_DB: Record<string, Player> = {
  '100105': {
    id: '100105',
    name: 'Denzel Dumfries',
    shortName: 'D. Dumfries',
    avatar: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=300&auto=format&fit=crop&q=80',
    rating: 85,
    maxRating: 96,
    position: 'RB',
    cardType: 'highlight',
    stars: 5,
    booster: {
      name: 'Duels +4',
      stats: ['defensiveAwareness', 'tackling', 'aggression', 'physicalContact'],
      value: 4
    },
    playstyle: 'Offensive Wingback',
    nation: 'Netherlands',
    club: 'Marlboro FC',
    league: 'Italian League',
    height: 188,
    weight: 80,
    age: 29,
    preferredFoot: 'Right',
    weakFootUsage: 'Medium',
    weakFootAccuracy: 'Medium',
    form: 'Unwavering',
    injuryResistance: 'Medium',
    skills: [
      'Through Passing',
      'Pinpoint Crossing',
      'Heading',
      'Acrobatic Finishing',
      'One-touch Pass',
      'Outside Curler',
      'Long Throw',
      'Interception',
      'Fighting Spirit',
      'Aerial Superiority'
    ],
    baseStats: {
      offensiveAwareness: 75,
      ballControl: 81,
      dribbling: 84,
      tightPossession: 77,
      lowPass: 85,
      loftedPass: 85,
      finishing: 68,
      heading: 76,
      placeKicking: 61,
      curl: 74,
      defensiveAwareness: 71,
      defensiveEngagement: 74,
      tackling: 71,
      aggression: 82,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 91,
      acceleration: 85,
      kickingPower: 87,
      jump: 80,
      physicalContact: 87,
      balance: 76,
      stamina: 91
    },
    maxAllocation: {
      shooting: 4,
      passing: 8,
      dribbling: 6,
      dexterity: 8,
      lowerBody: 10,
      aerial: 6,
      defending: 12
    }
  },
  '105674': {
    id: '105674',
    name: 'Lionel Messi',
    shortName: 'L. Messi',
    avatar: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=300&auto=format&fit=crop&q=80',
    rating: 90,
    maxRating: 103,
    position: 'AMF',
    cardType: 'bigtime',
    stars: 5,
    booster: {
      name: 'Stribling +4',
      stats: ['ballControl', 'dribbling', 'tightPossession', 'balance'],
      value: 4
    },
    playstyle: 'Creative Playmaker',
    nation: 'Argentina',
    club: 'Barcelona BP',
    league: 'Spanish League',
    height: 170,
    weight: 72,
    age: 33,
    preferredFoot: 'Left',
    weakFootUsage: 'Medium',
    weakFootAccuracy: 'High',
    form: 'Unwavering',
    injuryResistance: 'High',
    skills: [
      'Double Touch',
      'Sole Control',
      'Long Range Drive',
      'One-touch Pass',
      'Through Passing',
      'Outside Curler',
      'Acrobatic Finishing',
      'Captaincy',
      'Fighting Spirit'
    ],
    baseStats: {
      offensiveAwareness: 88,
      ballControl: 93,
      dribbling: 95,
      tightPossession: 94,
      lowPass: 89,
      loftedPass: 81,
      finishing: 87,
      heading: 65,
      placeKicking: 88,
      curl: 87,
      defensiveAwareness: 42,
      defensiveEngagement: 45,
      tackling: 43,
      aggression: 45,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 84,
      acceleration: 88,
      kickingPower: 83,
      jump: 68,
      physicalContact: 67,
      balance: 95,
      stamina: 82
    },
    maxAllocation: {
      shooting: 8,
      passing: 6,
      dribbling: 10,
      dexterity: 12,
      lowerBody: 8,
      aerial: 2
    }
  },
  '300981': {
    id: '300981',
    name: 'Neymar Jr',
    shortName: 'Neymar Jr',
    avatar: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=300&auto=format&fit=crop&q=80',
    rating: 88,
    maxRating: 101,
    position: 'LWF',
    cardType: 'showtime',
    stars: 5,
    booster: {
      name: 'Agility +4',
      stats: ['acceleration', 'balance', 'dribbling', 'tightPossession'],
      value: 4
    },
    playstyle: 'Creative Playmaker',
    nation: 'Brazil',
    club: 'Santos SF',
    league: 'Brazilian League',
    height: 175,
    weight: 68,
    age: 26,
    preferredFoot: 'Right',
    weakFootUsage: 'Medium',
    weakFootAccuracy: 'High',
    form: 'Standard',
    injuryResistance: 'Medium',
    skills: [
      'Double Touch',
      'Flip Flap',
      'Marseille Turn',
      'Sole Control',
      'Long Range Drive',
      'Chip Shot Control',
      'Through Passing',
      'Rabona',
      'Outside Curler'
    ],
    baseStats: {
      offensiveAwareness: 84,
      ballControl: 91,
      dribbling: 94,
      tightPossession: 90,
      lowPass: 85,
      loftedPass: 79,
      finishing: 80,
      heading: 58,
      placeKicking: 82,
      curl: 83,
      defensiveAwareness: 38,
      defensiveEngagement: 40,
      tackling: 35,
      aggression: 42,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 86,
      acceleration: 91,
      kickingPower: 80,
      jump: 62,
      physicalContact: 60,
      balance: 92,
      stamina: 78
    },
    maxAllocation: {
      shooting: 6,
      passing: 4,
      dribbling: 12,
      dexterity: 10,
      lowerBody: 8,
      aerial: 1
    }
  },
  '400101': {
    id: '400101',
    name: 'Erling Haaland',
    shortName: 'E. Haaland',
    avatar: 'https://images.unsplash.com/photo-1541252260730-0412e8e2108e?w=300&auto=format&fit=crop&q=80',
    rating: 87,
    maxRating: 99,
    position: 'CF',
    cardType: 'potw',
    stars: 5,
    booster: {
      name: 'Striker +3',
      stats: ['offensiveAwareness', 'finishing', 'kickingPower', 'physicalContact'],
      value: 3
    },
    playstyle: 'Goal Poacher',
    nation: 'Norway',
    club: 'Marlboro FC',
    league: 'English League',
    height: 194,
    weight: 88,
    age: 23,
    preferredFoot: 'Left',
    weakFootUsage: 'Medium',
    weakFootAccuracy: 'Medium',
    form: 'Standard',
    injuryResistance: 'High',
    skills: [
      'Heading',
      'Long Range Shooting',
      'Rising Shot',
      'Acrobatic Finishing',
      'One-touch Pass',
      'Super-sub',
      'Fighting Spirit'
    ],
    baseStats: {
      offensiveAwareness: 90,
      ballControl: 74,
      dribbling: 72,
      tightPossession: 70,
      lowPass: 68,
      loftedPass: 64,
      finishing: 91,
      heading: 82,
      placeKicking: 62,
      curl: 65,
      defensiveAwareness: 30,
      defensiveEngagement: 32,
      tackling: 28,
      aggression: 45,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 92,
      acceleration: 86,
      kickingPower: 90,
      jump: 84,
      physicalContact: 89,
      balance: 72,
      stamina: 80
    },
    maxAllocation: {
      shooting: 10,
      dribbling: 4,
      dexterity: 8,
      lowerBody: 8,
      aerial: 6
    }
  },
  // Custom characters matching Peter Parker's circle
  '500101': {
    id: '500101',
    name: 'Giorno Giovanna',
    shortName: 'G. Giovanna',
    avatar: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=300&auto=format&fit=crop&q=80',
    rating: 88,
    maxRating: 101,
    position: 'AMF',
    cardType: 'epic',
    stars: 5,
    booster: {
      name: 'Resolve (Stand)',
      stats: ['speed', 'ballControl', 'balance', 'stamina'],
      value: 3
    },
    playstyle: 'Creative Playmaker',
    nation: 'Italy',
    club: 'Passion Golden Wind',
    league: 'Anime League',
    height: 172,
    weight: 64,
    age: 15,
    preferredFoot: 'Right',
    weakFootUsage: 'Slightly',
    weakFootAccuracy: 'Very High',
    form: 'Unwavering',
    injuryResistance: 'High',
    skills: [
      'Double Touch',
      'Marseille Turn',
      'One-touch Pass',
      'Through Passing',
      'Outside Curler',
      'Captaincy',
      'Fighting Spirit',
      'Heel Trick'
    ],
    baseStats: {
      offensiveAwareness: 86,
      ballControl: 90,
      dribbling: 91,
      tightPossession: 88,
      lowPass: 92,
      loftedPass: 87,
      finishing: 78,
      heading: 65,
      placeKicking: 80,
      curl: 82,
      defensiveAwareness: 55,
      defensiveEngagement: 60,
      tackling: 58,
      aggression: 65,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 85,
      acceleration: 89,
      kickingPower: 79,
      jump: 74,
      physicalContact: 68,
      balance: 91,
      stamina: 87
    },
    maxAllocation: {
      shooting: 4,
      passing: 10,
      dribbling: 8,
      dexterity: 8,
      lowerBody: 6,
      defending: 2
    }
  },
  '500102': {
    id: '500102',
    name: 'Sans the Skeleton',
    shortName: 'Sans',
    avatar: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=300&auto=format&fit=crop&q=80',
    rating: 84,
    maxRating: 95,
    position: 'GK',
    cardType: 'epic',
    stars: 5,
    booster: {
      name: 'Bad Time',
      stats: ['gkReflexes', 'acceleration', 'balance', 'stamina'],
      value: 4
    },
    playstyle: 'Defensive Goalkeeper',
    nation: 'Underground',
    club: 'Underground Skeletons',
    league: 'Cosmic League',
    height: 150,
    weight: 50,
    age: 30,
    preferredFoot: 'Left',
    weakFootUsage: 'Almost Never',
    weakFootAccuracy: 'Low',
    form: 'Standard',
    injuryResistance: 'Low',
    skills: [
      'Interception',
      'Clearing',
      'GK Penalty Saver',
      'GK High Point Catch',
      'GK Low Reach',
      'Fighting Spirit',
      'Captaincy'
    ],
    baseStats: {
      offensiveAwareness: 40,
      ballControl: 70,
      dribbling: 65,
      tightPossession: 85,
      lowPass: 75,
      loftedPass: 70,
      finishing: 40,
      heading: 40,
      placeKicking: 40,
      curl: 80,
      defensiveAwareness: 82,
      defensiveEngagement: 85,
      tackling: 80,
      aggression: 75,
      gkAwareness: 90,
      gkCatching: 88,
      gkParrying: 92,
      gkReflexes: 96,
      gkReach: 89,
      speed: 80,
      acceleration: 99, // teleportation!
      kickingPower: 70,
      jump: 90,
      physicalContact: 40,
      balance: 98,
      stamina: 45 // lazy bone!
    },
    maxAllocation: {
      defending: 6,
      gk1: 10,
      gk2: 12,
      gk3: 8,
      dexterity: 8,
      lowerBody: 4
    }
  },
  '500103': {
    id: '500103',
    name: 'Squirrel Girl (Doreen)',
    shortName: 'Squirrel Girl',
    avatar: 'https://images.unsplash.com/photo-1544698310-74ea9d1c8258?w=300&auto=format&fit=crop&q=80',
    rating: 86,
    maxRating: 98,
    position: 'ST',
    cardType: 'highlight',
    stars: 5,
    booster: {
      name: 'Squirrel Swarm',
      stats: ['speed', 'acceleration', 'balance', 'offensiveAwareness'],
      value: 4
    },
    playstyle: 'Goal Poacher',
    nation: 'USA',
    club: 'Underground Skeletons',
    league: 'Cosmic League',
    height: 165,
    weight: 58,
    age: 20,
    preferredFoot: 'Right',
    weakFootUsage: 'Medium',
    weakFootAccuracy: 'High',
    form: 'Unwavering',
    injuryResistance: 'High',
    skills: [
      'Double Touch',
      'Heading',
      'Acrobatic Finishing',
      'Super-sub',
      'Fighting Spirit',
      'Aerial Superiority',
      'Track Back'
    ],
    baseStats: {
      offensiveAwareness: 88,
      ballControl: 82,
      dribbling: 84,
      tightPossession: 81,
      lowPass: 72,
      loftedPass: 68,
      finishing: 86,
      heading: 80,
      placeKicking: 60,
      curl: 65,
      defensiveAwareness: 65,
      defensiveEngagement: 72,
      tackling: 62,
      aggression: 88,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 92,
      acceleration: 94,
      kickingPower: 83,
      jump: 92,
      physicalContact: 81,
      balance: 93,
      stamina: 89
    },
    maxAllocation: {
      shooting: 8,
      dribbling: 6,
      dexterity: 10,
      lowerBody: 8,
      aerial: 6,
      defending: 4
    }
  },
  '500104': {
    id: '500104',
    name: 'Spider-Man (Peter Parker)',
    shortName: 'Spider-Man',
    avatar: 'https://images.unsplash.com/photo-1608889175123-8ec330b86f84?w=300&auto=format&fit=crop&q=80',
    rating: 89,
    maxRating: 101,
    position: 'LWF',
    cardType: 'epic',
    stars: 5,
    booster: {
      name: 'Spider-Sense',
      stats: ['speed', 'acceleration', 'balance', 'defensiveEngagement'],
      value: 4
    },
    playstyle: 'Roaming Flank',
    nation: 'USA',
    club: 'Underground Skeletons',
    league: 'Cosmic League',
    height: 178,
    weight: 74,
    age: 21,
    preferredFoot: 'Right',
    weakFootUsage: 'Medium',
    weakFootAccuracy: 'Very High',
    form: 'Unwavering',
    injuryResistance: 'High',
    skills: [
      'Double Touch',
      'Flip Flap',
      'Sole Control',
      'Acrobatic Finishing',
      'Interception',
      'Sliding Tackle',
      'Fighting Spirit',
      'Aerial Superiority',
      'Marseille Turn'
    ],
    baseStats: {
      offensiveAwareness: 87,
      ballControl: 89,
      dribbling: 92,
      tightPossession: 91,
      lowPass: 81,
      loftedPass: 75,
      finishing: 82,
      heading: 78,
      placeKicking: 68,
      curl: 74,
      defensiveAwareness: 68,
      defensiveEngagement: 74,
      tackling: 70,
      aggression: 72,
      gkAwareness: 40,
      gkCatching: 40,
      gkParrying: 40,
      gkReflexes: 40,
      gkReach: 40,
      speed: 95,
      acceleration: 97,
      kickingPower: 86,
      jump: 96,
      physicalContact: 82,
      balance: 97,
      stamina: 94
    },
    maxAllocation: {
      shooting: 6,
      passing: 4,
      dribbling: 10,
      dexterity: 10,
      lowerBody: 10,
      aerial: 4,
      defending: 4
    }
  }
};

export const INITIAL_POSTS: CommunityPost[] = [
  {
    id: 'post1',
    title: '🔥 Max Overall Build for Big Time Lionel Messi (103 AMF)',
    author: 'eFootball_Guru',
    content: 'This build maximizes his creative playmaker potential by focusing specifically on dexterity, tight space dribbling, and curl. Combined with Guardiola s 88 possession Manager style, he becomes absolute royalty in midfield. Let me know your thoughts!',
    upvotes: 412,
    commentsCount: 23,
    tags: ['Build Sharing', 'Messi', 'AMF'],
    playerId: '105674',
    buildPoints: {
      shooting: 8,
      passing: 6,
      dribbling: 10,
      dexterity: 12,
      lowerBody: 8,
      aerial: 2,
      defending: 0,
      gk1: 0,
      gk2: 0,
      gk3: 0
    },
    createdAt: '2026-06-20T10:15:30Z'
  },
  {
    id: 'post2',
    title: '⚡ Giorno Giovanna AMF Build! Gold Experience Resolve',
    author: 'StandUser99',
    content: 'If you enable his "Resolve" booster and utilize Zeitzler Klopp quick counter, his pace hits 94 on the pitch. His through passes have an S-Tier curve!',
    upvotes: 215,
    commentsCount: 14,
    tags: ['Build Sharing', 'Easter Egg', 'Creative Playmaker'],
    playerId: '500101',
    buildPoints: {
      shooting: 4,
      passing: 10,
      dribbling: 8,
      dexterity: 8,
      lowerBody: 6,
      aerial: 0,
      defending: 2,
      gk1: 0,
      gk2: 0,
      gk3: 0
    },
    createdAt: '2026-06-21T08:24:12Z'
  },
  {
    id: 'post3',
    title: '💀 SANS THE SKELETON GK AUTO BUILD IS CRAZY',
    author: 'MegalovaniaFC',
    content: 'His Reflexes hit 99 with the Bad Time booster + Manager stats! He is literally untouchable unless you hit him with real aerial aggression since his physical contact is only 40.',
    upvotes: 618,
    commentsCount: 45,
    tags: ['Sans', 'GK Build', 'Unbeatable'],
    playerId: '500102',
    buildPoints: {
      shooting: 0,
      passing: 0,
      dribbling: 0,
      dexterity: 8,
      lowerBody: 4,
      aerial: 0,
      defending: 6,
      gk1: 10,
      gk2: 12,
      gk3: 8
    },
    createdAt: '2026-06-21T12:05:00Z'
  }
];

export const POSITION_WEIGHTS: Record<string, Record<keyof PlayerStats, number>> = {
  ST: {
    offensiveAwareness: 0.16, ballControl: 0.08, dribbling: 0.08, tightPossession: 0.08,
    lowPass: 0.02, loftedPass: 0.01, finishing: 0.18, heading: 0.07, placeKicking: 0.01, curl: 0.02,
    defensiveAwareness: 0.0, defensiveEngagement: 0.0, tackling: 0.0, aggression: 0.0,
    speed: 0.08, acceleration: 0.09, kickingPower: 0.06, jump: 0.04, physicalContact: 0.05, balance: 0.04, stamina: 0.03,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  CF: {
    offensiveAwareness: 0.16, ballControl: 0.08, dribbling: 0.08, tightPossession: 0.08,
    lowPass: 0.02, loftedPass: 0.01, finishing: 0.18, heading: 0.07, placeKicking: 0.01, curl: 0.02,
    defensiveAwareness: 0.0, defensiveEngagement: 0.0, tackling: 0.0, aggression: 0.0,
    speed: 0.08, acceleration: 0.09, kickingPower: 0.06, jump: 0.04, physicalContact: 0.05, balance: 0.04, stamina: 0.03,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  SS: {
    offensiveAwareness: 0.13, ballControl: 0.11, dribbling: 0.11, tightPossession: 0.11,
    lowPass: 0.06, loftedPass: 0.03, finishing: 0.11, heading: 0.02, placeKicking: 0.02, curl: 0.03,
    defensiveAwareness: 0.0, defensiveEngagement: 0.0, tackling: 0.0, aggression: 0.0,
    speed: 0.07, acceleration: 0.08, kickingPower: 0.05, jump: 0.02, physicalContact: 0.03, balance: 0.08, stamina: 0.04,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  LWF: {
    offensiveAwareness: 0.10, ballControl: 0.14, dribbling: 0.15, tightPossession: 0.12,
    lowPass: 0.04, loftedPass: 0.05, finishing: 0.08, heading: 0.0, placeKicking: 0.02, curl: 0.05,
    defensiveAwareness: 0.0, defensiveEngagement: 0.0, tackling: 0.0, aggression: 0.0,
    speed: 0.10, acceleration: 0.11, kickingPower: 0.03, jump: 0.0, physicalContact: 0.02, balance: 0.10, stamina: 0.05,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  RWF: {
    offensiveAwareness: 0.10, ballControl: 0.14, dribbling: 0.15, tightPossession: 0.12,
    lowPass: 0.04, loftedPass: 0.05, finishing: 0.08, heading: 0.0, placeKicking: 0.02, curl: 0.05,
    defensiveAwareness: 0.0, defensiveEngagement: 0.0, tackling: 0.0, aggression: 0.0,
    speed: 0.10, acceleration: 0.11, kickingPower: 0.03, jump: 0.0, physicalContact: 0.02, balance: 0.10, stamina: 0.05,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  AMF: {
    offensiveAwareness: 0.08, ballControl: 0.13, dribbling: 0.11, tightPossession: 0.12,
    lowPass: 0.14, loftedPass: 0.08, finishing: 0.07, heading: 0.0, placeKicking: 0.02, curl: 0.03,
    defensiveAwareness: 0.0, defensiveEngagement: 0.0, tackling: 0.0, aggression: 0.0,
    speed: 0.04, acceleration: 0.07, kickingPower: 0.04, jump: 0.0, physicalContact: 0.02, balance: 0.11, stamina: 0.06,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  CMF: {
    offensiveAwareness: 0.05, ballControl: 0.10, dribbling: 0.08, tightPossession: 0.08,
    lowPass: 0.15, loftedPass: 0.12, finishing: 0.03, heading: 0.02, placeKicking: 0.02, curl: 0.03,
    defensiveAwareness: 0.06, defensiveEngagement: 0.06, tackling: 0.06, aggression: 0.05,
    speed: 0.05, acceleration: 0.05, kickingPower: 0.05, jump: 0.02, physicalContact: 0.05, balance: 0.07, stamina: 0.09,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  DMF: {
    offensiveAwareness: 0.0, ballControl: 0.05, dribbling: 0.04, tightPossession: 0.04,
    lowPass: 0.12, loftedPass: 0.08, finishing: 0.0, heading: 0.05, placeKicking: 0.0, curl: 0.0,
    defensiveAwareness: 0.15, defensiveEngagement: 0.13, tackling: 0.14, aggression: 0.12,
    speed: 0.05, acceleration: 0.04, kickingPower: 0.03, jump: 0.05, physicalContact: 0.10, balance: 0.02, stamina: 0.10,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  LMF: {
    offensiveAwareness: 0.07, ballControl: 0.11, dribbling: 0.12, tightPossession: 0.10,
    lowPass: 0.09, loftedPass: 0.11, finishing: 0.05, heading: 0.0, placeKicking: 0.02, curl: 0.04,
    defensiveAwareness: 0.04, defensiveEngagement: 0.04, tackling: 0.04, aggression: 0.04,
    speed: 0.09, acceleration: 0.09, kickingPower: 0.04, jump: 0.0, physicalContact: 0.03, balance: 0.07, stamina: 0.09,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  RMF: {
    offensiveAwareness: 0.07, ballControl: 0.11, dribbling: 0.12, tightPossession: 0.10,
    lowPass: 0.09, loftedPass: 0.11, finishing: 0.05, heading: 0.0, placeKicking: 0.02, curl: 0.04,
    defensiveAwareness: 0.04, defensiveEngagement: 0.04, tackling: 0.04, aggression: 0.04,
    speed: 0.09, acceleration: 0.09, kickingPower: 0.04, jump: 0.0, physicalContact: 0.03, balance: 0.07, stamina: 0.09,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  CB: {
    offensiveAwareness: 0.0, ballControl: 0.02, dribbling: 0.0, tightPossession: 0.0,
    lowPass: 0.05, loftedPass: 0.02, finishing: 0.0, heading: 0.12, placeKicking: 0.0, curl: 0.0,
    defensiveAwareness: 0.20, defensiveEngagement: 0.16, tackling: 0.18, aggression: 0.14,
    speed: 0.05, acceleration: 0.03, kickingPower: 0.02, jump: 0.10, physicalContact: 0.14, balance: 0.0, stamina: 0.05,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  LB: {
    offensiveAwareness: 0.04, ballControl: 0.06, dribbling: 0.05, tightPossession: 0.04,
    lowPass: 0.08, loftedPass: 0.12, finishing: 0.0, heading: 0.02, placeKicking: 0.02, curl: 0.04,
    defensiveAwareness: 0.12, defensiveEngagement: 0.09, tackling: 0.11, aggression: 0.07,
    speed: 0.11, acceleration: 0.09, kickingPower: 0.03, jump: 0.03, physicalContact: 0.05, balance: 0.05, stamina: 0.11,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  RB: {
    offensiveAwareness: 0.04, ballControl: 0.06, dribbling: 0.05, tightPossession: 0.04,
    lowPass: 0.08, loftedPass: 0.12, finishing: 0.0, heading: 0.02, placeKicking: 0.02, curl: 0.04,
    defensiveAwareness: 0.12, defensiveEngagement: 0.09, tackling: 0.11, aggression: 0.07,
    speed: 0.11, acceleration: 0.09, kickingPower: 0.03, jump: 0.03, physicalContact: 0.05, balance: 0.05, stamina: 0.11,
    gkAwareness: 0, gkCatching: 0, gkParrying: 0, gkReflexes: 0, gkReach: 0
  },
  GK: {
    offensiveAwareness: 0, ballControl: 0, dribbling: 0, tightPossession: 0,
    lowPass: 0.02, loftedPass: 0.02, finishing: 0, heading: 0, placeKicking: 0, curl: 0,
    defensiveAwareness: 0, defensiveEngagement: 0, tackling: 0, aggression: 0,
    speed: 0.02, acceleration: 0.02, kickingPower: 0, jump: 0.05, physicalContact: 0.05, balance: 0, stamina: 0.02,
    gkAwareness: 0.22, gkCatching: 0.18, gkParrying: 0.18, gkReflexes: 0.22, gkReach: 0.18
  }
};
